<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class InicioGraphicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function graphicClient($id)
    {
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
            $query = DB::select("SELECT COUNT(*) AS 'counts', 'Enero' AS 'customerType', 'yellow1' AS 'color' FROM cliente WHERE fcrea like '$anio-01%' AND id_empresa = $id UNION 
        SELECT COUNT(*) AS 'counts', 'Febrero' AS 'customerType', 'yellow2' AS 'color' FROM cliente WHERE fcrea like '$anio-02%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Marzo' AS 'customerType', 'yellow3' AS 'color' FROM cliente WHERE fcrea like '$anio-03%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Abril' AS 'customerType', 'green1' AS 'color' FROM cliente WHERE fcrea like '$anio-04%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Mayo' AS 'customerType', 'green2' AS 'color' FROM cliente WHERE fcrea like '$anio-05%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Junio' AS 'customerType', 'green3' AS 'color' FROM cliente WHERE fcrea like '$anio-06%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Julio' AS 'customerType', 'blue1' AS 'color' FROM cliente WHERE fcrea like '$anio-07%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Agosto' AS 'customerType', 'purple1' AS 'color' FROM cliente WHERE fcrea like '$anio-08%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Septiembre' AS 'customerType', 'purple1: ' AS 'color' FROM cliente WHERE fcrea like '$anio-09%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Octubre' AS 'customerType', 'fusia1' AS 'color' FROM cliente WHERE fcrea like '$anio-10%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Noviembre' AS 'customerType', 'orange1' AS 'color' FROM cliente WHERE fcrea like '$anio-11%' AND id_empresa = $id UNION
        SELECT COUNT(*) AS 'counts', 'Diciembre' AS 'customerType', 'orange2' AS 'color' FROM cliente WHERE fcrea like '$anio-12%' AND id_empresa = $id");
        $series = [];
        for ($i = 0; $i < count($query); $i++) {
            array_push($series, $query[$i]->counts);
        }
        $array = array("analyticsData" => $query, "series" => $series);
        return $array;
    }
    public function graphicVentasTotalesBar($id)
    {
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
        $query = DB::select("SELECT 'Ene' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id} UNION 
        SELECT 'Feb' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id} UNION
        SELECT 'Mar' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id} UNION
        SELECT 'Abr' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id} UNION
        SELECT 'May' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id} UNION
        SELECT 'Jun' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id} UNION
        SELECT 'Jul' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id} UNION
        SELECT 'Ago' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id} UNION
        SELECT 'Sep' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id} UNION
        SELECT 'Oct' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id} UNION
        SELECT 'Nov' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id} UNION
        SELECT 'Dic' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END AS 'counts' FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id}");
        $data = [];
        $total = 0;
        for ($i = 0; $i < count($query); $i++) {
            array_push($data, strval(round($query[$i]->counts, 2)));
            $total += $query[$i]->counts;
        }
        $total = " $ " . (strval(round($total, 2)));
        $array = array(array("data" => $data, "total" => $total));

        return $array;
    }
    public function graphicVentasVendedorBar($id)
    {
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
        $array = [];
        $vendedores = DB::select("SELECT * FROM vendedor WHERE id_empresa = $id");
        $countvendedores = count($vendedores);
        for ($i = 0; $i < $countvendedores; $i++) {
            $query = DB::select("SELECT 'Ene' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-01%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-01%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Feb' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-02%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-02%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Mar' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-03%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-03%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Abr' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-04%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-04%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'May' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-05%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-05%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Jun' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-06%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-06%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Jul' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-07%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-07%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Ago' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-08%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-08%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Sep' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-09%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-09%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Oct' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-10%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-10%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Nov' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-11%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-11%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor} UNION
            SELECT 'Dic' AS 'mes', CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) AS 'cant', CONCAT(ROUND(( (CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor})) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id}) - (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id}) AS counts FROM factura WHERE modo = 1 AND estado = 1	AND fecha_emision LIKE '$anio-12%' AND id_empresa = {$id}) * 100 ),2),'%') AS counts FROM factura WHERE modo=1 AND estado=1 AND  fcrea like '$anio-12%' AND id_empresa = {$id} AND id_vendedor = {$vendedores[$i]->id_vendedor};");
            $data = [];
            $cantidad = [];
            for ($j = 0; $j < count($query); $j++) {
                array_push($data, $query[$j]->counts);
                array_push($cantidad, $query[$j]->cant);
            }
            array_push($array, array("name" => $vendedores[$i]->nombre_vendedor, "data" => $data, "cantidad" => $cantidad));
        }

        return $array;
    }
    public function graphicCuentasPagar($id)
    {
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
        $ctaspagar = DB::select("SELECT SUM(valor_cuota) - SUM(valor_pagado) AS 'total', ROUND(( (SUM(valor_cuota) - SUM(valor_pagado)) / (SELECT CASE WHEN SUM(total_factura) IS NULL THEN 0 ELSE SUM(total_factura) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND id_empresa = {$id})-(SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND id_empresa = {$id}) FROM factura_compra WHERE id_empresa = {$id}) * 100 )) AS 'series' FROM ctas_pagar WHERE id_empresa ={$id}");
        $data = array("total" => $ctaspagar[0]->total, "series" => array($ctaspagar[0]->series));
        return $data;
     }
     public function graphicCuentasCobrar($id)
     {
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
         $ctaspagar = DB::select("SELECT SUM(valor_cuota) - SUM(valor_pagado) AS 'total', ROUND(( (SUM(valor_cuota) - SUM(valor_pagado)) / (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END + (SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_debito WHERE modo = 1 AND estado = 1 AND id_empresa = {$id})-(SELECT CASE WHEN SUM(valor_total) IS NULL THEN 0 ELSE SUM(valor_total) END FROM nota_credito WHERE modo = 1 AND estado = 1 AND id_empresa = {$id}) FROM factura WHERE modo = 1 AND estado = 1 AND id_empresa = {$id}) * 100 )) AS 'series' FROM ctas_cobrar WHERE id_empresa ={$id}");
         $data = array("total" => $ctaspagar[0]->total, "series" => array($ctaspagar[0]->series));
         return $data;
      }
      public function graphicUtilidades($id){
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
        $data=[];
        $empresa = DB::select("SELECT id_plan_cuentas_ingreso, id_plan_cuentas_costo, id_plan_cuentas_gasto FROM empresa WHERE id_empresa = {$id};");
        $qcta_ingreso = DB::select("SELECT codcta FROM plan_cuentas WHERE id_plan_cuentas = {$empresa[0]->id_plan_cuentas_ingreso};");
        $qcta_costo = DB::select("SELECT codcta FROM plan_cuentas WHERE id_plan_cuentas = {$empresa[0]->id_plan_cuentas_costo};");
        $qcta_gasto = DB::select("SELECT codcta FROM plan_cuentas WHERE id_plan_cuentas = {$empresa[0]->id_plan_cuentas_gasto};");
        $cta_ingreso = $qcta_ingreso[0]->codcta[0];
        $cta_costo = $qcta_costo[0]->codcta[0];
        $cta_gasto = $qcta_gasto[0]->codcta[0];
        $plan_cuentas = DB::select("SELECT id_plan_cuentas, codcta FROM plan_cuentas WHERE id_empresa = {$id};");
        $cuentas_ingreso = [];
        $cuentas_costo = [];
        $cuentas_gasto = [];
        for ($i=0; $i < count($plan_cuentas); $i++) { 
            if ($plan_cuentas[$i]->codcta[0] === $cta_ingreso && substr($plan_cuentas[$i]->codcta, -1) != ".") {
                array_push($cuentas_ingreso, $plan_cuentas[$i]->id_plan_cuentas);               
            }
            if ($plan_cuentas[$i]->codcta[0] === $cta_costo && substr($plan_cuentas[$i]->codcta, -1) != ".") {
                array_push($cuentas_costo, $plan_cuentas[$i]->id_plan_cuentas);               
            }
            if ($plan_cuentas[$i]->codcta[0] === $cta_gasto && substr($plan_cuentas[$i]->codcta, -1) != ".") {
                array_push($cuentas_gasto, $plan_cuentas[$i]->id_plan_cuentas);               
            }
        }
        $cuentas_ingreso =implode(",", $cuentas_ingreso);
        $cuentas_costo =implode(",", $cuentas_costo);
        $cuentas_gasto =implode(",", $cuentas_gasto);
        //valor ingresos totales por mes
        $qasientos_ingreso = DB::select("SELECT 'Ene' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-01%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Feb' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-02%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Mar' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-03%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Abr' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-04%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'May' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-05%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Jun' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-06%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Jul' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-07%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Ago' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-08%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Sep' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-09%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Oct' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-10%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Nov' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-11%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso}) UNION
        SELECT 'Dic' AS 'mes', SUM(ad.haber) AS 'ingreso' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-12%' AND ad.id_plan_cuentas IN ({$cuentas_ingreso});");
        //valor costo totales por mes
        $qasientos_costo = DB::select("SELECT 'Ene' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-01%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Feb' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-02%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Mar' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-03%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Abr' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-04%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'May' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-05%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Jun' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-06%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Jul' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-07%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Ago' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-08%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Sep' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-09%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Oct' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-10%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Nov' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-11%' AND ad.id_plan_cuentas IN ({$cuentas_costo}) UNION
        SELECT 'Dic' AS 'mes', SUM(ad.debe) AS 'costo' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-12%' AND ad.id_plan_cuentas IN ({$cuentas_costo});");
        //valor gastos totasles por mes
        $qasientos_gasto = DB::select("SELECT 'Ene' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-01%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Feb' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-02%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Mar' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-03%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Abr' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-04%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'May' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-05%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Jun' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-06%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Jul' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-07%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Ago' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-08%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Sep' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-09%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Oct' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-10%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Nov' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-11%' AND ad.id_plan_cuentas IN ({$cuentas_gasto}) UNION
        SELECT 'Dic' AS 'mes', SUM(ad.debe) AS 'gasto' FROM asientos_detalle ad INNER JOIN asientos a ON ad.id_asientos = a.id_asientos  WHERE a.fecha LIKE '$anio-12%' AND ad.id_plan_cuentas IN ({$cuentas_gasto});");
        
        $utilidad_bruta=[];
        $utilidad_neta=[];
        for ($j=0; $j < 12; $j++) { 
            array_push($utilidad_bruta, ($qasientos_ingreso[$j]->ingreso - $qasientos_costo[$j]->costo));
            array_push($utilidad_neta, ($qasientos_ingreso[$j]->ingreso - ($qasientos_costo[$j]->costo + $qasientos_gasto[$j]->gasto)));
        }
        $total_utilidad_bruta= array_sum($utilidad_bruta);
        $total_utilidad_neta= array_sum($utilidad_neta);
        
        $data = array( "series"=> array(array("name" => "Neta", "data" => $utilidad_neta), array("name" => "Bruta", "data" => $utilidad_bruta)), "utilitad_bruta_total" => round($total_utilidad_bruta, 2), "utilitad_neta_total" => round($total_utilidad_neta, 2));
        return $data;
      }
      public function graphicChequesPagar($id){
        $empresa_peri=DB::select("SELECT periodo_empresa from empresa where id_empresa=$id");
        $anio="2022";
        if(count($empresa_peri)>0){
            $anio=$empresa_peri[0]->periodo_empresa;
        }
        $data = DB::select("SELECT asientos_detalle.*,asientos.codigo,asientos.concepto,asientos.id_asientos_comprobante, IF(asientos.id_asientos_comprobante=7,(SELECT id_proveedor FROM factura_compra WHERE factura_compra.id_factcompra=asientos.codigo_rol),(SELECT id_proveedor FROM ctas_pagar_pagos WHERE ctas_pagar_pagos.id_ctas_pagar_pagos=asientos.codigo_rol)) AS id_proveedor,IF(asientos.id_asientos_comprobante=7,(SELECT beneficiario FROM factura_compra,proveedor WHERE factura_compra.id_factcompra=asientos.codigo_rol AND factura_compra.id_proveedor=proveedor.id_proveedor),(SELECT beneficiario FROM ctas_pagar_pagos,proveedor WHERE ctas_pagar_pagos.id_ctas_pagar_pagos=asientos.codigo_rol AND ctas_pagar_pagos.id_proveedor=proveedor.id_proveedor)) AS beneficiario FROM asientos_detalle INNER JOIN forma_pagos ON forma_pagos.id_forma_pagos=asientos_detalle.id_forma_pagos INNER JOIN asientos ON asientos.id_asientos=asientos_detalle.id_asientos WHERE forma_pagos.id_empresa={$id} AND forma_pagos.tipo_forma_pago='Cheque' AND asientos.id_asientos_comprobante IN (7,9) AND asientos_detalle.fecha_de_pago BETWEEN DATE_ADD(CURDATE(), INTERVAL (-WEEKDAY (CURDATE())) DAY) AND DATE_ADD(CURDATE(), INTERVAL (6 -WEEKDAY(CURDATE())) DAY);");
        return $data;
      }
}
